[package]
name = "aero"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.0-rc.3", features = ["dynamic_linking", "wayland"] }
avian3d = { git = "https://github.com/Jondolf/avian", branch = "main" }

[profile.dev.package."*"]
opt-level = 3

